services:
  server_0:
    image: ${IMAGE}
    command: ${COMMAND}
    environment:
      - MODEL_ID_OR_PATH=${MODEL_ID_OR_PATH}
      - HF_HOME=/snapshots/huggingface
      - HF_TOKEN=${HF_TOKEN}
    devices:
     - /dev/neuron0:/dev/neuron0
    shm_size: 16Gb
    volumes:
      - ${HOME}/scripts/triton:/scripts:ro
      - ${HOME}/snapshots:/snapshots:rw
      - ${HOME}/cache:/cache:rw
    ports:
      - "8080:8080"